addSbtPlugin("com.eed3si9n"      % "sbt-assembly"       % "2.3.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"       % "2.5.2")
addSbtPlugin("com.github.sbt"    % "sbt-release"        % "1.4.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"         % "5.10.0")
addCompilerPlugin("com.olegpy"  %% "better-monadic-for" % "0.3.1")
