# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI
on:
  pull_request:
  push:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 8
          - os: ubuntu-latest
            java: 11
          - os: ubuntu-latest
            java: 17
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: sbt

      - name: Install sbt
        shell: bash
        run: |
          echo "Installing sbt..."
          curl -L https://github.com/sbt/sbt/releases/download/v1.9.8/sbt-1.9.8.tgz | tar xz -C $HOME
          echo "$HOME/sbt/bin" >> $GITHUB_PATH

      - name: Build and Test
        run: sbt -v +test

      - name: Create header and run scalafmt
        run: sbt headerCreateAll scalafmtAll

      # Optional: This step uploads information to the GitHub dependency graph and unblocking Dependabot alerts for the repository
      #- name: Upload dependency graph
      # uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
